[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://janta-seva-backend.herokuapp.com/api"
  VITE_ML_API_URL = "https://your-ml-service-url.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200